# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://hudsonglass.com
title: Hudson Glass Inc.
email: jeff@hudsonglass.com
author: Jeff Lewis
description: > # "Write an awesome description for your new site here. 
  Hudson Glass Inc. Your Source for Stained Glass & Supplies
copyright: 'Copyright &copy; 2015 Hudson Glass. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/Hudson-Glass-Co-Inc-56222241451
  - title: yelp
    url: https://www.yelp.com/biz/hudson-glass-co-inc-peekskill
  - title: linkedin
    url: https://www.linkedin.com/in/jeff-lewis-59902a32/
